### PR TITLE
Port to kernel 5.6

### LINKED ISSUE #6: Does not compile with kernel 5.6
```
+ cd /scratch/build-kmod-pciedummy
+ sudo -H -E -u msk_jenkins make install DESTDIR=../install
In file included from /scratch/source/mtcadummy.h:39,
                 from /scratch/source/mtcadummy_drv.c:1:
/scratch/source/pciedev_io.h:60:18: error: field 'start_time' has incomplete type
   60 |   struct timeval start_time;
      |                  ^~~~~~~~~~
/scratch/source/pciedev_io.h:61:18: error: field 'stop_time' has incomplete type
   61 |   struct timeval stop_time;
      |                  ^~~~~~~~~
make[6]: *** [/usr/src/linux-5.6.0-1/scripts/Makefile.build:269: /scratch/source/mtcadummy_drv.o] Error 1
make[5]: *** [/usr/src/linux-5.6.0-1/Makefile:1698: /scratch/source] Error 2
make[4]: *** [../../../linux-5.6.0-1/Makefile:180: sub-make] Error 2
make[3]: *** [Makefile:9: all] Error 2
make[2]: *** [CMakeFiles/kmod.dir/build.make:74: CMakeFiles/kmod] Error 2
make[1]: *** [CMakeFiles/Makefile2:93: CMakeFiles/kmod.dir/all] Error 2
make: *** [Makefile:158: all] Error 2
```

### PR DESCRIPTION
**Pull request by phako**
Use new APIs from kernel 5.6

Fixes #6

### CODE REVIEW

**Comment by phako** [comment]
Checked against DeviceAccess tests which still pass
